---
title: "Visualization Practice"
author: "William T. Bickelmann"
date: 2017-09-25T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

```{r}
library(Lahman)
library(dplyr)
library(ggplot2)
library(ggiraph)
```

First to Wrangel Data
```{r}
Batting%>%
  group_by(playerID)%>%
  summarize(Career_HR=sum(HR),Career_SO=sum(SO))%>%
  filter(Career_HR>=400)->df
```

Now an Inner Join
```{r}
HR_vs_SO<-inner_join(df,Master,by=c("playerID"))%>%
  select(nameFirst,nameLast,Career_HR,Career_SO)
```

#----------------------------------------------------------------------------------
Next to make it a visualization
  
```{r}

g<-ggplot()+
  geom_point(data=HR_vs_SO, aes(x=Career_SO,y=Career_HR)) +
  ggtitle("Career Homeruns vs. Strikeouts for Great Hitters") +
  xlab("Strikeouts") +
  ylab("Homeruns")
g
```
Now to make it interactive

```{r}
ggiraph(code=print(g),hover_css="fill:white;stroke:black")

```



